name: Fruits et Noms

on:
  workflow_dispatch:   # déclenchement manuel

jobs:
  manger:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true   # si un job échoue, les autres s'arrêtent
      matrix:
        fruit: [pomme, banane, fraise, orange]
        nom: [Michel, Sophie, Karim]

    steps:
      - name: Phrase personnalisée
        run: echo "${{ matrix.nom }} mange une ${{ matrix.fruit }}, et il adore ça !"
